apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotation:
    projectcontour.io/tls-minimum-protocol-version: "TLSv1_3"
    ingress.kubernetes.io/force-ssl-redirect: "false"
    ingress.kubernetes.io/rewrite-target: "/"
    kubernetes.io/ingress.class: "contour"
  name: monitoring-httpproxy
  namespace: tanzu-system-monitoring
spec:
  virtualhost:
    fqdn: pro.cnd.lab
    tls:
      secretName: cnd-tls/wild-tls
  routes:
    - conditions:
      - prefix: "/"
      pathRewritePolicy:
        replacePrefix:
          - prefix: "/"
            replacement: /
      services:
        - name: prometheus-server
          port: 80
    - conditions:
      - prefix: "/alertmanager/"
      pathRewritePolicy:
        replacePrefix:
        - prefix: "/alertmanager/"
          replacement: /
      services:
        - name: prometheus-alertmanager
          port: 80

