apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: elk-cluster
  namespace: elk-stack
spec:
  distribution:
    version: v1.18.5+vmware.1-tkg.1.c40d30d
  topology:
    controlPlane:
      count: 1
      class: best-effort-small
      storageClass: tanzu-storage-policy
    workers:
      count: 3
      class: best-effort-xlarge
      storageClass: tanzu-storage-policy
  settings:
    storage:
      defaultClass: tanzu-storage-policy
    network:
      cni:
        name: antrea
      services:
        cidrBlocks: ["20.20.16.0/21"]
      pods:
        cidrBlocks: ["20.20.0.0/21"]
