apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  labels:
    name: nfs-pv
spec:
  capacity:
    storage: 50Gi
  storageClassName: nfs-storage-policy
  accessModes:
  - ReadWriteMany
  nfs:
    server: 172.19.1.212
    path: /nas-data
